### ISSUE TITLE
JS - Order Page, Button - make the sandwich

### ISSUE THREAD

**Issue by Katedam** [Katedam/Jam-Time#28]
write a function that makes a button with an eventlistener that when clicked will 
- Collect all of the "true" form field's (ones that have been selected) values and store in sandwich object array within matching username/password object, call save to local storage function to store new data
BUT if it’s a guest, meaning no matching username and password found, save to guest array to store temporarily for summary page

**Comment by bizzybits** [comment]
this issue was merged with other issues and taken over by Kate and Zach
