### ISSUE TITLE
JS - Order-Summary Page, Button - load Summary page

### ISSUE THREAD

**Issue by Katedam** [Katedam/Jam-Time#29]
Write a function that Loads order summary page and populates the summary div with the sandwich ingredients the user has ordered/stored in their data (but only the lastest selections, not the entire list of saved sandwiches)
- if user is a guest - show last index object in guest array which should be their sandwich and load address input field
- If its a registered user account and an address has been saved (ie not an empty string), add address to summary page instead of address input field.

**Comment by Zachar13y** [comment]
Done.
